[package]
name = "gears-node"
version = "0.1.0"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "gears_node"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
